apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iyd409xlu-dotnet-basic
  janus-idp.io/tekton: iyd409xlu-dotnet-basic
  backstage.io/kubernetes-id: iyd409xlu-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iyd409xlu-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
